name: Build and Publish

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - uses: actions/upload-artifact@v2
        with:
          name: win64
          path: bin/Release/net7.0

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download win64 Artifact
        uses: actions/download-artifact@v2
        with:
          name: win64
          path: bin/Release/net7.0

      - name: Generate auth code
        id: generate
        uses: CyberAndrii/steam-totp@master
        with:
          shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}
          time_offset: 15

      - name: Publish
        uses: game-ci/steam-deploy@v2
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          totp: ${{ steps.generate.outputs.code }}
          appId: 1882990
          buildDescription: Automatic build.
          rootPath: bin
          depot2Path: Release/net7.0
          releaseBranch: prerelease
